### ISSUE TITLE
issue with refresh inventory

### ISSUE THREAD

**Issue by mehdia4ever** [fitbeard/awx-without-k8s#45]
i have this issue when a update the inventory

I use only one server with hybride node

Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/tasks/receptor.py", line 435, in _run_internal
    lines = resultfile.readlines()
OSError: read() should have returned a bytes object, not 'NoneType'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/tasks/jobs.py", line 593, in run
    res = receptor_job.run()
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/tasks/receptor.py", line 317, in run
    res = self._run_internal(receptor_ctl)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/tasks/receptor.py", line 444, in _run_internal
    raise RuntimeError(detail)
RuntimeError: exit status 1

**Comment by fitbeard** [comment]
Resolved: https://github.com/fitbeard/awx-without-k8s/pull/44

**Comment by fitbeard** [comment]
@mehdia4ever you are using wrong EE value for `hybrid` setup. That is to say: 

https://github.com/fitbeard/awx-without-k8s/blob/master/roles/awx/defaults/main.yml#L32

From README:

Create [`custom Docker image`](./docker/Dockerfile.awx-ee) for execution nodes and for management nodes (**if `awx_node_role_type` variable is set to `hybrid`**).

Or use `quay.io/tadas/awx-without-k8s-ee:latest` image which is based on the [`same Dockerfile`](./docker/Dockerfile.awx-ee).
```

**Comment by mehdia4ever** [comment]
Thanks for your feedback.

i used your EE image quay.io/tadas/awx-without-k8s-ee:latest, bbut i still have another issue running refresh inventory.

WARN[0000] "/" is not a shared mount, this could cause issues or missing mounts with rootless containers 
ERRO[0000] running `/usr/bin/newuidmap 232 0 1000 1 1 100000 65536`: newuidmap: write to uid_map failed: Operation not permitted 
Error: cannot set up namespace using "/usr/bin/newuidmap": should have setuid or have filecaps setuid: exit status 1

**Comment by fitbeard** [comment]
Please force pull tag `latest`, o use tag `21.14.0`. This is fixed after this commit: https://github.com/fitbeard/awx-without-k8s/pull/44

**Comment by fitbeard** [comment]
You don't neet to use this image for execution environments. You can use ANY EE for your needs inside AWX. But for container on the host in hybrid setup you need to use proper image because in this setup you are running container(s) inside container (awx-ee). Read my comment about `awx_ee_image_url` value above.
